### ISSUE TITLE
ESP32 and ESP8266 UART API is not documented

### ISSUE THREAD

**Issue by mattytrentini** [mattytrentini/micropython#6]
PyBoard does cover UART though it's limited:

https://docs.micropython.org/en/latest/pyboard/quickref.html#uart-serial-bus

**Comment by dpgeorge** [comment]
The generic machine.UART should cover most things for this.

**Comment by mattytrentini** [comment]
Resolved. See [ESP32 Quickref/UART](https://docs.micropython.org/en/latest/esp32/quickref.html#uart-serial-bus) and [machine.UART](https://docs.micropython.org/en/latest/library/machine.UART.html#machine-uart).
