### ISSUE TITLE
ESP32 Timer identifier needs documenting

### ISSUE THREAD

**Issue by dpgeorge** [mattytrentini/micropython#7]
The current esp32 quickref states that `-1` is a valid Timer id, for software timers.  But this is not true, there are actually 4 timers with ids 0-3.  For example `Timer(-1)` and `Timer(3)` are equivalent.

**Comment by mattytrentini** [comment]
Resolved, see [ESP32 Quickref/Timers](https://docs.micropython.org/en/latest/esp32/quickref.html#timers).
