### ISSUE TITLE
Missing (`u`)`random` documentation

### ISSUE THREAD

**Issue by HowManyOliversAreThere** [mattytrentini/micropython#9]
There appears to be no documentation for `random` / `urandom` whatsoever. This should be resolved.

ESP8266 implementation only appears to implement `random.getrandbits()`, whereas ESP32 provides multiple useful functions.

**Comment by mattytrentini** [comment]
Added by Niti:

https://github.com/micropython/micropython/commits/master/docs/library/random.rst
